<a href="https://colab.research.google.com/github/sangramshitole07/AMLAssignment/blob/main/AMLAssignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Problem 1: Create a constant array

In [1]:
import numpy as np

# Create a 2x2 array filled with 7s
constant_array = np.full((2, 2), 7)
display(constant_array)


array([[7, 7],
       [7, 7]])

## Problem 2: Create an array filled with random values

In [2]:
import numpy as np

# Create a 2x2 array filled with random values between 0 and 1
random_array = np.random.rand(2, 2)
display(random_array)


array([[0.75405629, 0.29010517],
       [0.65703799, 0.33588983]])

## Problem 3: Create a NumPy array containing the numbers from 10 to 50. Display: The array, Number of elements, Shape, Dimension, Data type

In [3]:
import numpy as np

# Create array from 10 to 50 (inclusive)
arr = np.arange(10, 51)

print("Array:", arr)
print("Number of elements:", arr.size)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data type:", arr.dtype)


Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


## Problem 4: Using NumPy, create: A 1D array containing 10 zeros, A 3 × 3 array containing ones, A 4 × 4 identity matrix, An array containing numbers from 5 to 50 with a step size of 5.

In [4]:
import numpy as np

# 1D array containing 10 zeros
zeros_array = np.zeros(10)
print("1D array of 10 zeros:", zeros_array)

# 3x3 array containing ones
ones_array = np.ones((3, 3))
print("\n3x3 array of ones:\n", ones_array)

# 4x4 identity matrix
identity_matrix = np.eye(4)
print("\n4x4 identity matrix:\n", identity_matrix)

# Array from 5 to 50 with a step size of 5
stepped_array = np.arange(5, 51, 5)
print("\nArray from 5 to 50 with step 5:", stepped_array)


1D array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

3x3 array of ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

4x4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array from 5 to 50 with step 5: [ 5 10 15 20 25 30 35 40 45 50]


## Problem 5: Create an array containing numbers from 1 to 24. Reshape it into: 4 × 6, 6 × 4, 2 × 3 × 4. Display the shape and ndim of each result.

In [5]:
import numpy as np

# Create array from 1 to 24
arr = np.arange(1, 25)

# Reshape to 4x6
arr_4x6 = arr.reshape(4, 6)
print("Reshaped to 4x6:")
print("  Array:\n", arr_4x6)
print("  Shape:", arr_4x6.shape)
print("  Dimension:", arr_4x6.ndim)

# Reshape to 6x4
arr_6x4 = arr.reshape(6, 4)
print("\nReshaped to 6x4:")
print("  Array:\n", arr_6x4)
print("  Shape:", arr_6x4.shape)
print("  Dimension:", arr_6x4.ndim)

# Reshape to 2x3x4
arr_2x3x4 = arr.reshape(2, 3, 4)
print("\nReshaped to 2x3x4:")
print("  Array:\n", arr_2x3x4)
print("  Shape:", arr_2x3x4.shape)
print("  Dimension:", arr_2x3x4.ndim)


Reshaped to 4x6:
  Array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
  Shape: (4, 6)
  Dimension: 2

Reshaped to 6x4:
  Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
  Shape: (6, 4)
  Dimension: 2

Reshaped to 2x3x4:
  Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
  Shape: (2, 3, 4)
  Dimension: 3


## Problem 6: Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81]). Write NumPy statements to display: First element, Last element, Third element, First four elements, Last three elements.

In [6]:
import numpy as np

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

print("Original marks array:", marks)
print("First element:", marks[0])
print("Last element:", marks[-1])
print("Third element:", marks[2])
print("First four elements:", marks[:4])
print("Last three elements:", marks[-3:])


Original marks array: [78 85 92 67 88 73 95 81]
First element: 78
Last element: 81
Third element: 92
First four elements: [78 85 92 67]
Last three elements: [73 95 81]


## Problem 7: Create: a = np.array([10, 20, 30, 40, 50]), b = np.array([5, 10, 15, 20, 25]). Calculate: a + b, a - b, a * b, a / b, Square of every element in a.

In [7]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

print("Array a:", a)
print("Array b:", b)
print("\na + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("Square of every element in a:", a**2)


Array a: [10 20 30 40 50]
Array b: [ 5 10 15 20 25]

a + b: [15 30 45 60 75]
a - b: [ 5 10 15 20 25]
a * b: [  50  200  450  800 1250]
a / b: [2. 2. 2. 2. 2.]
Square of every element in a: [ 100  400  900 1600 2500]


## Problem 8: Given: salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000]). Find: Total salary, Average salary, Highest salary, Lowest salary, Median salary, Standard deviation.

In [8]:
import numpy as np

salary = np.array([25000, 32000, 28000, 45000,
                   50000, 38000, 42000, 30000])

print("Salary array:", salary)
print("Total salary:", np.sum(salary))
print("Average salary:", np.mean(salary))
print("Highest salary:", np.max(salary))
print("Lowest salary:", np.min(salary))
print("Median salary:", np.median(salary))
print("Standard deviation:", np.std(salary))


Salary array: [25000 32000 28000 45000 50000 38000 42000 30000]
Total salary: 290000
Average salary: 36250.0
Highest salary: 50000
Lowest salary: 25000
Median salary: 35000.0
Standard deviation: 8317.902379807063


## Problem 9: Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84]). Using NumPy boolean indexing, find: Marks greater than 75, Marks between 50 and 80, Number of students who scored below 50, Percentage of students who scored 60 or above. Do not use a Python for loop.

In [9]:
import numpy as np

marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])

print("Original marks array:", marks)

# Marks greater than 75
marks_gt_75 = marks[marks > 75]
print("\nMarks greater than 75:", marks_gt_75)

# Marks between 50 and 80 (inclusive of 50, exclusive of 80)
marks_between_50_80 = marks[(marks >= 50) & (marks < 80)]
print("Marks between 50 and 80:", marks_between_50_80)

# Number of students who scored below 50
students_below_50 = np.sum(marks < 50)
print("Number of students who scored below 50:", students_below_50)

# Percentage of students who scored 60 or above
students_60_or_above = np.sum(marks >= 60)
percentage_60_or_above = (students_60_or_above / len(marks)) * 100
print(f"Percentage of students who scored 60 or above: {percentage_60_or_above:.2f}%")


Original marks array: [45 78 89 32 67 90 55 76 41 84]

Marks greater than 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Number of students who scored below 50: 3
Percentage of students who scored 60 or above: 60.00%


## Problem 10: The following array contains marks of four students in three subjects: marks = np.array([[80, 75, 90], [65, 70, 72], [88, 92, 85], [55, 60, 58]]). Calculate: Total marks of each student, Average marks of each student, Average marks in each subject, Student with the highest total, Highest mark in each subject.

In [10]:
import numpy as np

marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])

print("Marks array:\n", marks)

# Total marks of each student (sum across columns, axis=1)
total_marks_per_student = np.sum(marks, axis=1)
print("\nTotal marks of each student:", total_marks_per_student)

# Average marks of each student
average_marks_per_student = np.mean(marks, axis=1)
print("Average marks of each student:", average_marks_per_student)

# Average marks in each subject (sum across rows, axis=0)
average_marks_per_subject = np.mean(marks, axis=0)
print("Average marks in each subject:", average_marks_per_subject)

# Student with the highest total
highest_total_student_index = np.argmax(total_marks_per_student)
print(f"Student with the highest total (index {highest_total_student_index}): {total_marks_per_student[highest_total_student_index]}")

# Highest mark in each subject
highest_mark_per_subject = np.max(marks, axis=0)
print("Highest mark in each subject:", highest_mark_per_subject)


Marks array:
 [[80 75 90]
 [65 70 72]
 [88 92 85]
 [55 60 58]]

Total marks of each student: [245 207 265 173]
Average marks of each student: [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject: [72.   74.25 76.25]
Student with the highest total (index 2): 265
Highest mark in each subject: [88 92 90]


## Problem 11: Create: A = np.array([[1, 2], [3, 4]]), B = np.array([[5, 6], [7, 8]]). Perform: Matrix addition, Element-wise multiplication, Matrix multiplication, Transpose of A. Explain the difference between: A * B and A @ B

In [11]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)

# Matrix addition
matrix_addition = A + B
print("\nMatrix Addition (A + B):\n", matrix_addition)

# Element-wise multiplication
elementwise_multiplication = A * B
print("\nElement-wise Multiplication (A * B):\n", elementwise_multiplication)

# Matrix multiplication
matrix_multiplication = A @ B
print("\nMatrix Multiplication (A @ B):\n", matrix_multiplication)

# Transpose of A
transpose_A = A.T
print("\nTranspose of A:\n", transpose_A)

print("\nExplanation of A * B vs A @ B:")
print("  `A * B` performs element-wise multiplication (Hadamard product). It multiplies corresponding elements of the two arrays.")
print("  `A @ B` performs matrix multiplication (dot product) according to the rules of linear algebra. For this to work, the number of columns in A must match the number of rows in B.")


Matrix A:
 [[1 2]
 [3 4]]

Matrix B:
 [[5 6]
 [7 8]]

Matrix Addition (A + B):
 [[ 6  8]
 [10 12]]

Element-wise Multiplication (A * B):
 [[ 5 12]
 [21 32]]

Matrix Multiplication (A @ B):
 [[19 22]
 [43 50]]

Transpose of A:
 [[1 3]
 [2 4]]

Explanation of A * B vs A @ B:
  `A * B` performs element-wise multiplication (Hadamard product). It multiplies corresponding elements of the two arrays.
  `A @ B` performs matrix multiplication (dot product) according to the rules of linear algebra. For this to work, the number of columns in A must match the number of rows in B.


## Problem 12: Daily temperatures for two weeks are: temperature = np.array([31, 32, 33, 35, 36, 34, 32, 30, 29, 31, 33, 35, 37, 36]). Find: Mean temperature, Maximum and minimum temperatures, Number of days above the average temperature, Temperatures greater than 34°C, Difference between maximum and minimum, Standard deviation.

In [12]:
import numpy as np

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

print("Temperature array:", temperature)

# Mean temperature
mean_temp = np.mean(temperature)
print("\nMean temperature:", mean_temp)

# Maximum and minimum temperatures
max_temp = np.max(temperature)
min_temp = np.min(temperature)
print("Maximum temperature:", max_temp)
print("Minimum temperature:", min_temp)

# Number of days above the average temperature
days_above_average = np.sum(temperature > mean_temp)
print("Number of days above the average temperature:", days_above_average)

# Temperatures greater than 34°C
temps_gt_34 = temperature[temperature > 34]
print("Temperatures greater than 34°C:", temps_gt_34)

# Difference between maximum and minimum
diff_max_min = max_temp - min_temp
print("Difference between maximum and minimum:", diff_max_min)

# Standard deviation
std_dev_temp = np.std(temperature)
print("Standard deviation:", std_dev_temp)


Temperature array: [31 32 33 35 36 34 32 30 29 31 33 35 37 36]

Mean temperature: 33.142857142857146
Maximum temperature: 37
Minimum temperature: 29
Number of days above the average temperature: 6
Temperatures greater than 34°C: [35 36 35 37 36]
Difference between maximum and minimum: 8
Standard deviation: 2.356060357495806


## Problem 13: Monthly sales of a company are: sales = np.array([12000, 15000, 17000, 14000, 18000, 21000, 19000, 22000, 25000, 23000, 26000, 28000]). Determine: Total annual sales, Average monthly sales, Month with the highest sales, Month with the lowest sales, Number of months with sales above ₹20,000, Percentage increase from January to December. Hint: Remember that NumPy indexing starts at 0, while month numbering normally starts at 1.

In [13]:
import numpy as np

sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

print("Monthly sales array:", sales)

# Total annual sales
total_annual_sales = np.sum(sales)
print("\nTotal annual sales:", total_annual_sales)

# Average monthly sales
average_monthly_sales = np.mean(sales)
print("Average monthly sales:", average_monthly_sales)

# Month with the highest sales (add 1 for 1-based indexing)
month_highest_sales = np.argmax(sales) + 1
print(f"Month with the highest sales: Month {month_highest_sales} (Sales: {sales[month_highest_sales-1]}) ")

# Month with the lowest sales (add 1 for 1-based indexing)
month_lowest_sales = np.argmin(sales) + 1
print(f"Month with the lowest sales: Month {month_lowest_sales} (Sales: {sales[month_lowest_sales-1]})")

# Number of months with sales above ₹20,000
months_above_20k = np.sum(sales > 20000)
print("Number of months with sales above ₹20,000:", months_above_20k)

# Percentage increase from January to December
january_sales = sales[0]
december_sales = sales[-1]
if january_sales != 0:
    percentage_increase = ((december_sales - january_sales) / january_sales) * 100
    print(f"Percentage increase from January to December: {percentage_increase:.2f}%")
else:
    print("Cannot calculate percentage increase as January sales are zero.")


Monthly sales array: [12000 15000 17000 14000 18000 21000 19000 22000 25000 23000 26000 28000]

Total annual sales: 240000
Average monthly sales: 20000.0
Month with the highest sales: Month 12 (Sales: 28000) 
Month with the lowest sales: Month 1 (Sales: 12000)
Number of months with sales above ₹20,000: 6
Percentage increase from January to December: 133.33%


## Problem 14: Consider marks of five students in four subjects: marks = np.array([[78, 85, 90, 88], [65, 70, 72, 68], [92, 88, 95, 91], [55, 60, 58, 62], [80, 75, 82, 79]]). Write a NumPy program that calculates: Total marks of every student, Average of every student, Average mark for every subject, Highest-scoring student, Lowest-scoring student, Students whose average is greater than 80, Overall class average. Then assign a performance category based on average: (table provided in prompt). Challenge: Try assigning these categories using np.where() or np.select() instead of a Python loop.

In [26]:
import numpy as np

marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])

print("Marks array:\n", marks)

# Total marks of every student (sum across columns, axis=1)
total_marks_students = np.sum(marks, axis=1)
print("\nTotal marks of every student:", total_marks_students)

# Average of every student
average_marks_students = np.mean(marks, axis=1)
print("Average marks of every student:", average_marks_students)

# Average mark for every subject (mean across rows, axis=0)
average_marks_subjects = np.mean(marks, axis=0)
print("Average mark for every subject:", average_marks_subjects)

# Highest-scoring student
highest_scoring_student_idx = np.argmax(total_marks_students)
print(f"Highest-scoring student (index {highest_scoring_student_idx}): Total {total_marks_students[highest_scoring_student_idx]}")

# Lowest-scoring student
lowest_scoring_student_idx = np.argmin(total_marks_students)
print(f"Lowest-scoring student (index {lowest_scoring_student_idx}): Total {total_marks_students[lowest_scoring_student_idx]}")

# Students whose average is greater than 80
students_avg_gt_80 = np.where(average_marks_students > 80)[0]
print("Students whose average is greater than 80 (indices):", students_avg_gt_80)

Marks array:
 [[78 85 90 88]
 [65 70 72 68]
 [92 88 95 91]
 [55 60 58 62]
 [80 75 82 79]]

Total marks of every student: [341 275 366 235 316]
Average marks of every student: [85.25 68.75 91.5  58.75 79.  ]
Average mark for every subject: [74.  75.6 79.4 77.6]
Highest-scoring student (index 2): Total 366
Lowest-scoring student (index 3): Total 235
Students whose average is greater than 80 (indices): [0 2]


In [15]:
import numpy as np

# Assuming marks and average_marks_students are defined from the previous cell
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])
average_marks_students = np.mean(marks, axis=1)

# Overall class average
overall_class_average = np.mean(marks)
print("Overall class average:", overall_class_average)

# Assign performance categories using np.select
conditions = [
    average_marks_students >= 85,
    (average_marks_students >= 70) & (average_marks_students < 85),
    (average_marks_students >= 50) & (average_marks_students < 70),
    average_marks_students < 50
]
categories = ['Excellent', 'Good', 'Average', 'Needs Improvement']

performance_categories = np.select(conditions, categories, default='Unknown')

print("\nPerformance Categories per student:")
for i, avg in enumerate(average_marks_students):
    print(f"  Student {i}: Average = {avg:.2f}, Category = {performance_categories[i]}")


Overall class average: 76.65

Performance Categories per student:
  Student 0: Average = 85.25, Category = Excellent
  Student 1: Average = 68.75, Category = Average
  Student 2: Average = 91.50, Category = Excellent
  Student 3: Average = 58.75, Category = Average
  Student 4: Average = 79.00, Category = Good


## Problem 15: Generate 20 random integers between 1 and 100.

In [16]:
import numpy as np

# Generate 20 random integers between 1 and 100 (inclusive)
random_integers = np.random.randint(1, 101, 20)
print("Generated random integers:", random_integers)


Generated random integers: [ 1 88 12 32 64 19 25 45 37 27  3 77 59 97 87 63 78 77  3 35]


## Problem 16: Find all even numbers from the generated array.

In [17]:
import numpy as np

# Re-using the array from Problem 15 for consistency
random_integers = np.random.randint(1, 101, 20)
print("Original array:", random_integers)

# Find even numbers using boolean indexing
even_numbers = random_integers[random_integers % 2 == 0]
print("Even numbers:", even_numbers)


Original array: [55 22 66 56 75 59 40 39 59 49 38  2 48 94 49 42 60 66 54 56]
Even numbers: [22 66 56 40 38  2 48 94 42 60 66 54 56]


## Problem 17: Replace values below 50 with 0.

In [18]:
import numpy as np

# Re-using the array from Problem 15 for consistency, but making a copy
arr_to_modify = np.random.randint(1, 101, 20)
print("Original array:", arr_to_modify)

# Replace values below 50 with 0
arr_to_modify[arr_to_modify < 50] = 0
print("Array after replacing values below 50 with 0:", arr_to_modify)


Original array: [ 14  60  77  90   4  44  82  27 100  39   8  81  35  72  42   4  30  77
  70   1]
Array after replacing values below 50 with 0: [  0  60  77  90   0   0  82   0 100   0   0  81   0  72   0   0   0  77
  70   0]


## Problem 18: Sort the array in ascending and descending order.

In [19]:
import numpy as np

# Re-using the array from Problem 15 for consistency
arr_to_sort = np.random.randint(1, 101, 20)
print("Original array:", arr_to_sort)

# Sort in ascending order
ascending_array = np.sort(arr_to_sort)
print("\nSorted in ascending order:", ascending_array)

# Sort in descending order
descending_array = np.sort(arr_to_sort)[::-1] # or -np.sort(-arr_to_sort)
print("Sorted in descending order:", descending_array)


Original array: [18 35 67 45 71 14 50 22 63 65 83 19 18 80 92  8 41 85 66 42]

Sorted in ascending order: [ 8 14 18 18 19 22 35 41 42 45 50 63 65 66 67 71 80 83 85 92]
Sorted in descending order: [92 85 83 80 71 67 66 65 63 50 45 42 41 35 22 19 18 18 14  8]


## Problem 19: Find unique values and their frequencies.

In [20]:
import numpy as np

# Re-using the array from Problem 15 for consistency
arr_for_unique = np.random.randint(1, 101, 20)
print("Original array:", arr_for_unique)

# Find unique values and their counts (frequencies)
unique_values, counts = np.unique(arr_for_unique, return_counts=True)

print("\nUnique values:", unique_values)
print("Frequencies:", counts)

# Display as a dictionary for clarity
freq_dict = dict(zip(unique_values, counts))
print("Unique values and their frequencies (dict):", freq_dict)


Original array: [90 73 40 40 53 68 12 76 51 97 33 19 72  2 69 83 54 15 16 80]

Unique values: [ 2 12 15 16 19 33 40 51 53 54 68 69 72 73 76 80 83 90 97]
Frequencies: [1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1]
Unique values and their frequencies (dict): {np.int64(2): np.int64(1), np.int64(12): np.int64(1), np.int64(15): np.int64(1), np.int64(16): np.int64(1), np.int64(19): np.int64(1), np.int64(33): np.int64(1), np.int64(40): np.int64(2), np.int64(51): np.int64(1), np.int64(53): np.int64(1), np.int64(54): np.int64(1), np.int64(68): np.int64(1), np.int64(69): np.int64(1), np.int64(72): np.int64(1), np.int64(73): np.int64(1), np.int64(76): np.int64(1), np.int64(80): np.int64(1), np.int64(83): np.int64(1), np.int64(90): np.int64(1), np.int64(97): np.int64(1)}


## Problem 20: Create a 5 × 5 random matrix and calculate row-wise and column-wise means.

In [21]:
import numpy as np

# Create a 5x5 random matrix (values between 0 and 100 for example)
random_matrix = np.random.randint(0, 101, (5, 5))
print("5x5 Random Matrix:\n", random_matrix)

# Calculate row-wise means (mean across columns, axis=1)
row_wise_means = np.mean(random_matrix, axis=1)
print("\nRow-wise Means:", row_wise_means)

# Calculate column-wise means (mean across rows, axis=0)
column_wise_means = np.mean(random_matrix, axis=0)
print("Column-wise Means:", column_wise_means)


5x5 Random Matrix:
 [[ 64  74  58  89  73]
 [ 14  60  82  50  67]
 [ 49   5  76  28  49]
 [ 32  21 100  51  49]
 [ 10  66  30  25  31]]

Row-wise Means: [71.6 54.6 41.4 50.6 32.4]
Column-wise Means: [33.8 45.2 69.2 48.6 53.8]


## Problem 21: Take your own example to normalize an array.

In [27]:
import numpy as np

# Example array for normalization (Min-Max Scaling)
# Formula: (X - min(X)) / (max(X) - min(X))

data = np.array([10, 20, 30, 40, 50, 100])
print("Original array:", data)

min_val = np.min(data)
max_val = np.max(data)

# Handle the case where all values are the same to avoid division by zero
if max_val - min_val == 0:
    normalized_data = np.zeros_like(data) # or data / max_val if max_val != 0
else:
    normalized_data = (data - min_val) / (max_val - min_val)

print("Normalized array (Min-Max Scaling):", normalized_data)

Original array: [ 10  20  30  40  50 100]
Normalized array (Min-Max Scaling): [0.         0.11111111 0.22222222 0.33333333 0.44444444 1.        ]


## Problem 22: Use your own data to standardize an array.

In [28]:
import numpy as np

# Example array for standardization (Z-score Normalization)
# Formula: (X - mean(X)) / std(X)

data = np.array([10, 12, 15, 12, 18, 20, 13, 16, 14, 17])
print("Original array:", data)

mean_val = np.mean(data)
std_val = np.std(data)

# Handle the case where standard deviation is zero to avoid division by zero
if std_val == 0:
    standardized_data = np.zeros_like(data) # All values would be the mean, so they become 0 after subtracting mean
else:
    standardized_data = (data - mean_val) / std_val

print("Standardized array (Z-score Normalization):", standardized_data)

Original array: [10 12 15 12 18 20 13 16 14 17]
Standardized array (Z-score Normalization): [-1.60175571 -0.92015754  0.10223973 -0.92015754  1.12463699  1.80623517
 -0.57935845  0.44303881 -0.23855936  0.7838379 ]


## Problem 23: Create a NumPy array containing 100 random exam marks and determine how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100.

In [24]:
import numpy as np

# Create 100 random exam marks between 0 and 100
exam_marks = np.random.randint(0, 101, 100)
print("Generated 100 random exam marks:\n", exam_marks)

# Determine counts for each range using boolean indexing
range_0_39 = np.sum((exam_marks >= 0) & (exam_marks <= 39))
range_40_59 = np.sum((exam_marks >= 40) & (exam_marks <= 59))
range_60_79 = np.sum((exam_marks >= 60) & (exam_marks <= 79))
range_80_100 = np.sum((exam_marks >= 80) & (exam_marks <= 100))

print("\nNumber of students in ranges:")
print(f"  0-39:   {range_0_39} students")
print(f"  40-59:  {range_40_59} students")
print(f"  60-79:  {range_60_79} students")
print(f"  80-100: {range_80_100} students")

# Verify total count
print(f"Total students counted: {range_0_39 + range_40_59 + range_60_79 + range_80_100}")
print(f"Original array length: {len(exam_marks)}")


Generated 100 random exam marks:
 [38 29 12 71 61 37 68 31 50 86 16 79 68  0 38  0 70 36 61 29 48 50 92  7
 68 37 21 66 61 51  0 86 76 41 39 73  7 79 92 46 44 32 72 52 39 91 93 80
 25 82 58 95 38  9 62 35 52  1  2  1 84 53 88 57 91 88 50 61 44  1 16 69
 45 30 10 41 24 19 91  6 24 36 12 16 64 15 81 56 43 97 60 96 88 16 32 30
  3 41 98 40]

Number of students in ranges:
  0-39:   42 students
  40-59:  20 students
  60-79:  19 students
  80-100: 19 students
Total students counted: 100
Original array length: 100


## Problem 24: Compare the time required to multiply 1,000,000 numbers using a Python list and a NumPy array.

In [25]:
import numpy as np
import time

num_elements = 1_000_000

# --- Python List ---
python_list_a = list(range(num_elements))
python_list_b = list(range(num_elements))

start_time = time.time()
python_result = [a * b for a, b in zip(python_list_a, python_list_b)]
end_time = time.time()
python_time = end_time - start_time
print(f"Time taken for Python list multiplication: {python_time:.6f} seconds")

# --- NumPy Array ---
numpy_array_a = np.arange(num_elements)
numpy_array_b = np.arange(num_elements)

start_time = time.time()
numpy_result = numpy_array_a * numpy_array_b
end_time = time.time()
numpy_time = end_time - start_time
print(f"Time taken for NumPy array multiplication: {numpy_time:.6f} seconds")

print(f"\nNumPy is approximately {python_time / numpy_time:.2f} times faster than Python lists for this operation.")


Time taken for Python list multiplication: 0.175616 seconds
Time taken for NumPy array multiplication: 0.005386 seconds

NumPy is approximately 32.61 times faster than Python lists for this operation.
