In [13]:
import numpy as np
import pandas as pd


In [14]:
from google.colab import files
uploaded=files.upload()
dataset=pd.read_csv("Social_Network_Ads.csv")
dataset

Saving Social_Network_Ads.csv to Social_Network_Ads (2).csv


,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [15]:
#Step 3: detailed Info of the dataset
print("Information about the dataset", dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB
Information about the dataset None


In [16]:
print("Description about the dataset",dataset.describe())

Description about the dataset             User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000


In [17]:
print("Checking column names : ",dataset.columns)

Checking column names :  Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')


In [18]:
dataset.isnull().sum()

,0
User ID,0
Gender,0
Age,0
EstimatedSalary,0
Purchased,0


In [19]:
X=dataset.iloc[:,[2,3]]
X

,Age,EstimatedSalary
0,19,19000
1,35,20000
2,26,43000
3,27,57000
4,19,76000
...,...,...
395,46,41000
396,51,23000
397,50,20000
398,36,33000


In [20]:
y=dataset.iloc[:,-1]
y

,Purchased
0,0
1,0
2,0
3,0
4,0
...,...
395,1
396,1
397,1
398,0


In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
X_test

array([[-0.54748976,  0.5130727 ],
       [ 0.15442019, -0.61825566],
       [-0.10879604,  0.14615539],
       [-0.54748976,  0.26846116],
       [-0.10879604, -0.61825566],
       [-0.81070599, -1.53554892],
       [-0.45975102, -1.68843113],
       [-0.0210573 ,  2.25592989],
       [-1.60035469, -0.0678797 ],
       [ 0.94406888, -0.83229075],
       [-0.54748976, -0.6488321 ],
       [-0.72296725, -0.46537345],
       [ 0.06668145, -0.46537345],
       [ 0.24215893,  0.20730828],
       [-1.4248772 ,  0.48249625],
       [-0.37201227,  1.43036596],
       [ 0.06668145,  0.20730828],
       [-1.51261594,  0.45191981],
       [ 1.64597884,  1.8278597 ],
       [-0.10879604, -1.47439603],
       [-0.10879604, -0.70998498],
       [ 0.94406888,  2.25592989],
       [ 0.41763642, -0.58767922],
       [ 0.94406888,  1.06344865],
       [-1.16166097, -1.29093738],
       [ 1.11954637,  2.16420057],
       [-0.72296725,  0.5130727 ],
       [-0.63522851,  0.2990376 ],
       [ 0.06668145,

In [23]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [24]:
y_pred=classifier.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1])

In [25]:
y_test

,Purchased
132,0
309,0
341,0
196,0
246,0
...,...
146,1
135,0
390,1
264,1


In [26]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm

array([[61,  7],
       [ 3, 29]])

In [29]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print('Accuracy Score',accuracy_score(y_test,y_pred)*100)
print('Precision Score',precision_score(y_test,y_pred)*100)

Accuracy Score 90.0
Precision Score 80.55555555555556


In [28]:
num_classes = cm.shape[0]
labels = np.unique(y_test)

print('\nMetrics per class (One-vs-Rest):')
# Iterate through each class to calculate its individual True Positives, False Positives, etc.
# This uses a 'one-vs-rest' approach, treating one class as positive and all others as negative.
for i, class_label in enumerate(labels):
    # True Positives (TP): Correctly predicted instances of the current class_label
    TP = cm[i, i]

    # False Positives (FP): Instances incorrectly predicted as the current class_label (actually another class)
    FP = cm[:, i].sum() - TP

    # False Negatives (FN): Instances of the current class_label incorrectly predicted as another class
    FN = cm[i, :].sum() - TP

    # True Negatives (TN): Instances correctly predicted as *not* the current class_label
    TN = cm.sum() - (TP + FP + FN)

    print(f'\nClass: {class_label}')
    print(f'  TP: {TP}')
    print(f'  FP: {FP}')
    print(f'  FN: {FN}')
    print(f'  TN: {TN}')


Metrics per class (One-vs-Rest):

Class: 0
  TP: 61
  FP: 3
  FN: 7
  TN: 29

Class: 1
  TP: 29
  FP: 7
  FN: 3
  TN: 61
